/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.gradleup.shadow") version("8.3.5")
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots")
    }

    maven {
        url = uri("http://jline.sourceforge.net/m2repo")
        isAllowInsecureProtocol = true
    }

    maven {
        url = uri("https://repository.johnymuffin.com/repository/maven-public/")
    }

    maven {
        url = uri("https://repository.johnymuffin.com/repository/maven-snapshots/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.bukkit:bukkit:0.0.1-POSEIDON")
    implementation("net.sf.jopt-simple:jopt-simple:6.0-alpha-3")
    implementation("jline:jline:0.9.93")
    implementation("org.xerial:sqlite-jdbc:3.7.2")
    implementation("mysql:mysql-connector-java:5.1.14")
    implementation("org.avaje:ebean:2.7.3")
    implementation("org.yaml:snakeyaml:2.0")
    implementation("com.google.guava:guava-collections:r03")
    implementation("org.jetbrains:annotations:20.0.0")
    implementation("com.google.guava:guava:32.0.0-jre")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("com.google.code.gson:gson:2.9.0")
    implementation(files("libs/ModLoaderMP.jar"))
}

group = "org.bukkit"
version = "1.1.10"
description = "Project Poseidon"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.withType(Jar::class) {
    manifest {
        attributes["Manifest-Version"] = "1.0"
        attributes["Created-By"] = "1.6.0"
        attributes["Specification-Title"] = "Bukkit"
        attributes["Main-Class"] = "org.bukkit.craftbukkit.Main"
        attributes["Specification-Version"] = "unknown"
        attributes["Specification-Vendor"] = "Bukkit Team"
        attributes["Implementation-Version"] = "git-Bukkit-0.0.0-980-g4ed23b1-b1060jnks"
        attributes["Implementation-Vendor"] = "Bukkit Team"
        attributes["Sealed"] = "true"
        attributes["Implementation-Title"] = "CraftBukkit"
    }
}